import 'package:isar_community/isar.dart';

part 'isar_coin.g.dart';

/// Isar collection representing a cryptocurrency coin for local storage.
@Collection()
class IsarCoin {
  IsarCoin({
    required this.id,
    required this.name,
    required this.symbol,
    required this.price,
    required this.imageUrl,
  }) : isarId = id.hashCode;

  /// Primary key generated by Isar. Must be nullable int.
  Id isarId;

  // Original API identifier (e.g., "btc"). Stored as a regular field.
  final String id;
  final String name;
  final String symbol;
  final double price;
  final String imageUrl;
}
